{{- range $name, $api := .Values.apis }}
{{- if $api.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
  namespace: {{ $.Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
      - name: {{ $name }}
        image: {{ default $name $api.image }}

        imagePullPolicy: {{ default "IfNotPresent" $.Values.imagePullPolicy }}
        resources:
          limits:
            cpu: {{ default "1000m" $api.resourcesLimitsCpu }}
            memory: {{ default "1024Mi" $api.resourcesLimitsMemory }}
          requests:
            cpu: {{ default "5m" $api.resourcesRequestsCpu }}
            memory: {{ default "64Mi" $api.resourcesRequestsMemory }}
        ports:
        - containerPort: 4000
          name: user-port
          protocol: TCP

        envFrom:
          - configMapRef:
              name: mds-env
        env:
          - name: PATH_PREFIX
            value: {{ $api.pathPrefix }}
          - name: PG_PASS
            valueFrom:
              secretKeyRef:
                name: mds-secrets
                key: postgresql-password
          {{- if $api.env }}
{{ toYaml $api.env | indent 10 }}
          {{- end }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mds-secrets
  namespace: {{ $.Release.Namespace }}
data:
  postgresql-password: {{ default "CHANGEME" .Values.postgresql.password | b64enc }}
type: Opaque
