{{- if $.Values.nats.host }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: backend-egress
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ printf "*.%s.svc.cluster.local" .Values.backendNamespace | quote }}
  ports:
  - number: 4222
    name: nats-client
    protocol: TCP
  - number: 9092
    name: kafka-client
    protocol: TCP
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: backend-disable-mtls
  namespace: {{ .Release.Namespace }}
spec:
  host: "*.backend.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: DISABLE
---
{{- end }}
{{- if (eq .Values.postgresql.internal false) }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: pg-rw-external
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ $.Values.postgresql.host }}
  ports:
  - number: {{ $.Values.postgresql.port }}
    name: tcp
    protocol: TCP
  location: MESH_EXTERNAL
---
{{- if .Values.postgresql.hostReader }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: pg-ro-external
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ $.Values.postgresql.hostReader }}
  ports:
  - number: {{ $.Values.postgresql.port }}
    name: tcp
    protocol: TCP
  location: MESH_EXTERNAL
---
{{- end }}
{{- end }}
{{- if (eq .Values.redis.internal false) }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: redis-external
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ .Values.redis.host }}
  ports:
  - number: {{ .Values.redis.port }}
    name: tcp
    protocol: TCP
  location: MESH_EXTERNAL
---
{{- end }}
