apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - "*.backend.svc.cluster.local"
  ports:
  - number: 4222
    name: client
    protocol: TCP
  - number: 9092
    name: kafka-client
    protocol: TCP
  - number: 6379
    name: redis
    protocol: TCP
  - number: 5432
    name: postgresql
    protocol: TCP
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: kafka
  namespace: {{ .Release.Namespace }}
spec:
  host: "*.backend.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: DISABLE
