{{- if .Values.istio.enabled }}

{{- range $ns := .Values.istio.backendNamespaces }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: backend-{{ $ns }}
spec:
  host: "*.{{ $ns }}.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: DISABLE
---
{{- end }}

{{- if (eq .Values.postgresql.internal false) }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: pg-rw-external
spec:
  hosts:
  - {{ $.Values.postgresql.host }}
  {{- if .Values.postgresql.hostReader }}
  - {{ $.Values.postgresql.hostReader }}
  {{- end }}
  ports:
  - number: {{ $.Values.postgresql.port }}
    name: tcp
    protocol: TCP
  location: MESH_EXTERNAL
{{- end }}
---
{{- if (eq .Values.redis.internal false) }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: redis-external
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ .Values.redis.host }}
  ports:
  - number: {{ .Values.redis.port }}
    name: tcp
    protocol: TCP
  location: MESH_EXTERNAL
---
{{- end }}

{{- end }}
