{{- if .Values.istio.enabled }}
{{- range $name, $deploy := .Values.deployments }}
{{- if $deploy.enabled }}
{{- if (hasKey $deploy "pathPrefix") }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $name }}-route
spec:
  hosts:
  - {{ $.Values.domain | quote }}
  gateways:
  - mds-gateway
  http:
  - match:
    - uri:
        regex: {{ printf "^%s($|/.*$)" $deploy.pathPrefix | quote }}
    route:
    - destination:
        host: {{ $name }}.{{ $.Release.Namespace }}.svc.cluster.local
        port:
          number: {{ $.Values.httpPort }}
    {{- if $.Values.istio.tls.elbTermination }}
    headers:
      request:
        set:
          x-forwarded-proto: https
    {{- end }}
    corsPolicy:
      allowOrigin:
      - "*"
      allowMethods:
      - POST
      - GET
      - HEAD
      - OPTIONS
      - PATCH
      - PUT
      - DELETE
      allowCredentials: false
      allowHeaders:
      - Content-Type
      - Authorization
      maxAge: "10m"
---
{{- end }}
{{- end }}
{{- end }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mds-gateway
spec:
  selector:
    istio: {{ .Values.istio.ingressgateway }}
  servers:
  {{- if .Values.istio.tls.enabled }}
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
  {{- else if .Values.istio.tls.elbTermination }}
  - port:
      number: 443
      name: http443
      protocol: HTTP
  {{- else }}
  - port:
      number: 80
      name: http
      protocol: HTTP
  {{- end }}
    hosts:
    - {{ .Values.domain | quote }}
{{- end }}
