{{- range $key, $api := .Values.apis }}
{{- if $api.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $key }}
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    app: {{ $key }}
  ports:
  - name: http-{{ $key }}
    port: {{ $api.port }}
    targetPort: {{ $api.port }}
{{- end }}
{{- end }}