{{- range $name, $api := .Values.apis }}
{{- if $api.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    app: {{ $name }}
  ports:
  - name: http-{{ $key }}
    port: {{ $api.port }}
    targetPort: {{ $api.port }}
{{- end }}
{{- end }}
