apis:
  mds-agency:
    enabled: true
    pathPrefix: /agency
  mds-audit:
    enabled: true
    pathPrefix: /audit
  mds-policy:
    enabled: true
    pathPrefix: /policy
  mds-compliance:
    enabled: true
    pathPrefix: /compliance
  mds-daily:
    enabled: true
    pathPrefix: /daily
  mds-jurisdiction:
    enabled: true
    pathPrefix: /jurisdiction
  mds-jurisdiction-service:
    enabled: true
  mds-policy-author:
    enabled: true
    pathPrefix: /policy
  mds-web-sockets:
    enabled: true
    pathPrefix: /web
  mds-geography:
    enabled: true
    pathPrefix: /geography
  mds-geography-author:
    enabled: true
    pathPrefix: /geography-author
tenantId: default
timezone: America/Los_Angeles
imagePullPolicy: IfNotPresent
domain: "*"
tls:
  enabled: false
  domain:
jwt:
  issuer:
  enabled: false
  bypassInternal: false
  firstInstall: false
  audiences: []
nats:
  enabled: false
  host:
  credentials: false
kafka:
  enabled: false
  host:
  port: 9092
postgresql:
  internal: true
  host:
  hostReader:
  port: 5432
  user: mdsadmin
  database: mds
redis:
  internal: true
  host:
  port: 6379
  usePassword: false
