apis:
  mds-agency:
    enabled: true
    pathPrefix: /agency
  mds-audit:
    enabled: true
    pathPrefix: /audit
  mds-policy:
    enabled: true
    pathPrefix: /policy
  mds-compliance:
    enabled: true
    pathPrefix: /compliance
  mds-daily:
    enabled: true
    pathPrefix: /daily
  mds-jurisdiction:
    enabled: true
    pathPrefix: /jurisdiction
  mds-jurisdiction-service:
    enabled: true
    pathPrefix: /jurisdiction
  mds-policy-author:
    enabled: true
    pathPrefix: /policy
  mds-web-sockets:
    enabled: true
    pathPrefix: /web
  mds-geography:
    enabled: true
    pathPrefix: /geography
  mds-geography-author:
    enabled: true
    pathPrefix: /geography-author
tenantId: default
timezone: America/Los_Angeles
imagePullPolicy: IfNotPresent
domain: "*"
tls:
  enabled: false
  domain:
jwt:
  issuer:
  enabled: false
  bypassInternal: false
  firstInstall: false
  audiences: []
postgresql:
  internal: true
  host:
  hostReader:
  port: 5432
  existingSecret: mds-secrets
  password: # for setting secret internally - not used by https://github.com/helm/charts/tree/master/stable/postgresql
  postgresqlUsername: mdsadmin
  postgresqlDatabase: mds
  image:
    repository: postgres
    tag: 10
redis:
  internal: true
  host:
  port: 6379
  usePassword: false
  cluster:
    enabled: false
  master:
    disableCommands: []
  slave:
    disableCommands: []
nats:
  internal: true
  clusterAuth:
    enabled: false
  host:
kafka:
  internal: true
  host:
